name: dart_logger
description: Configurable, Fast and Small logging library for dart and flutter
version: 0.0.1
homepage: https://github.com/muj-programmer/dart_logger
issue_tracker: https://github.com/muj-programmer/dart_logger/issues

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  io: ^0.3.3

dev_dependencies:
